FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build --configuration production


FROM nginx:alpine

# REMOVE default nginx site
RUN rm -rf /usr/share/nginx/html/*

# COPIA O BUILD CERTO DO ANGULAR (IMPORTANTE)
COPY --from=build /app/dist/fila-conferencia-frontend/ /usr/share/nginx/html/
# fallback SPA (IMPORTANTE PRA ANGULAR ROUTER)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]