FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN NODE_OPTIONS=--max-old-space-size=2048 npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

# 🔥 AQUI está o ajuste real
COPY --from=build /app/dist/fila-conferencia-frontend/browser/* /usr/share/nginx/html/

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]